REPORTS:
-   folder: '%Y-%m-%d Team A Daily'
    name: new report 
    from: sender.example.com
    subject: my report subject
    to: person_19@example.com, person_4@example.com, person_21@example.com
    body: 'this is a short body'
    tio_tags: 
    - Business Unit: Sales
    cspm_projects:
    - AWS CSPM
    - AWS Pipeline
